version: '3'
services:
  pass:
    image: pass
    command: sh
    volumes:
      - gnupg:/root/.gnupg
      - pass:/root/.password-store
  abook:
    image: abook
    command: abook
    volumes:
      - abook:/root/.abook
  gnupg:
    image: gnupg
    command: gpg --batch --generate-key "/root/envsubst/key.stat"
    volumes:
      - envsubst:/root/envsubst
      - gnupg:/root/.gnupg
  envsubst:
    image: gettext
    command: /root/envsubst/envsubst
    environment:
      - GIT_USER=${GIT_USER}
      - GIT_EMAIL=${GIT_EMAIL}
      - PASSPHRASE=${PASSPHRASE}
    volumes:
      - ./etc:/usr/profile
      - envsubst:/root/envsubst

  restic:
    image: restic
    command: restic backup $DATA --tag $PROJECT --tag $GIT_USER
    ports:
      - 8000
    environment:
      - PROJECT=${PROJECT}
      - GIT_USER=${GIT_USER}
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD}
      - DATA=${DATA}
    volumes:
      - pass:/root/.password-store
      - abook:/root/.abook
      - gnupg:/root/.gnupg
      - envsubst:/root/envsubst
      - restic:/usr/local/restic

volumes:
  pass: {}
  abook: {}
  gnupg: {}
  envsubst: {}
  restic: {}
