version: '3'
services:
  pass:
    image: pass
    command: sh # fixme: pass commands only work when running container, perhaps init pass and run show commands only during backup
    volumes:
      - gnupg:/root/.gnupg
      - pass:/root/.password-store
  abook:
    image: abook
    command: abook
    volumes:
      - abook:/root/.abook
  gnupg:
    image: gnupg
    command: gpg --batch --generate-key "/root/envsubst/key.stat"
    volumes:
      - envsubst:/root/envsubst
      - gnupg:/root/.gnupg
  envsubst:
    image: gettext
    command: /root/envsubst/envsubst
    environment:
      - GIT_USER=${GIT_USER}
      - GIT_EMAIL=${GIT_EMAIL}
      - PASSPHRASE=${PASSPHRASE}
    volumes:
      - ./etc:/usr/profile
      - envsubst:/root/envsubst

  restic:
    image: restic
    command: restic backup $DATA --tag $PROJECT --tag $GIT_USER
    environment:
      - PROJECT=${PROJECT}
      - GIT_USER=${GIT_USER}
      - RESTIC_REPOSITORY=/usr/local/restic
      - RESTIC_PASSWORD_COMMAND='pass show restic'
      - DATA='/root/.password-store /root/.abook /root/.gnupg /root/envsubst'
    volumes:
      - pass:/root/.password-store
      - abook:/root/.abook
      - gnupg:/root/.gnupg
      - envsubst:/root/envsubst
      - restic:/usr/local/restic

volumes:
  pass: {}
  abook: {}
  gnupg: {}
  envsubst: {}
  restic:
    external: true
